services:
  crazycake-db:
    image: postgres:15-alpine
    container_name: crazycake-db
    environment:
      POSTGRES_USER: crazycake-dev-db-user 
      POSTGRES_PASSWORD: crazycake-dev-db-password
      POSTGRES_DB: crazycake-dev-db
    ports:
      - "5432:5432"
    networks:
      - app-network

  crazycake-api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: crazycake-api
    command: sh -c "while [ ! -f /app/run.sh ]; do sleep 1; done; chmod +x /app/run.sh && /app/run.sh"
    expose:
      - "8080"
    environment:
      DATABASE_URL: postgresql://crazycake-dev-db-user:crazycake-dev-db-password@crazycake-db:5432/crazycake-dev-db
    depends_on:
      - crazycake-db
    networks:
      - app-network

  crazycake-nginx:
    image: nginx:latest
    container_name: crazycake-nginx
    ports:
      - "80:80"  # Updated to listen on port 80 internally
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - crazycake-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
