services:
  crazycake-db:
    image: postgres:15-alpine
    container_name: crazycake-db
    environment:
      POSTGRES_USER: crazycake-dev-db-user 
      POSTGRES_PASSWORD: crazycake-dev-db-password
      POSTGRES_DB: crazycake-dev-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network


  crazycake-api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: crazycake-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://crazycake-dev-db-user:crazycake
    depends_on:
      - crazycake-db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
